# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(613, 422)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/windowIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.runButton = QtWidgets.QPushButton(parent=Form)
        self.runButton.setGeometry(QtCore.QRect(110, 310, 75, 24))
        self.runButton.setObjectName("runButton")
        self.exitButton = QtWidgets.QPushButton(parent=Form)
        self.exitButton.setGeometry(QtCore.QRect(210, 310, 75, 24))
        self.exitButton.setObjectName("exitButton")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/windowIcon.png"))
        self.label_3.setObjectName("label_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 100, 431, 181))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(30, 30, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 54, 16))
        self.label_2.setObjectName("label_2")
        self.num2 = QtWidgets.QLineEdit(parent=self.page)
        self.num2.setGeometry(QtCore.QRect(70, 120, 113, 20))
        self.num2.setObjectName("num2")
        self.num1 = QtWidgets.QLineEdit(parent=self.page)
        self.num1.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.num1.setObjectName("num1")
        self.displayBrowser = QtWidgets.QTextBrowser(parent=self.page)
        self.displayBrowser.setGeometry(QtCore.QRect(200, 30, 201, 121))
        self.displayBrowser.setObjectName("displayBrowser")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(parent=self.page_2)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 301, 161))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icon/f8adac7d759066b26368c6c9fb04c66.jpg"))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_2)
        self.backButton = QtWidgets.QPushButton(parent=Form)
        self.backButton.setGeometry(QtCore.QRect(310, 310, 75, 24))
        self.backButton.setObjectName("backButton")
        self.nextButton = QtWidgets.QPushButton(parent=Form)
        self.nextButton.setGeometry(QtCore.QRect(400, 310, 75, 24))
        self.nextButton.setObjectName("nextButton")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "芝士雪豹"))
        self.runButton.setText(_translate("Form", "开始"))
        self.exitButton.setText(_translate("Form", "退出"))
        self.label.setText(_translate("Form", "数A"))
        self.label_2.setText(_translate("Form", "数B"))
        self.backButton.setText(_translate("Form", "上一页"))
        self.nextButton.setText(_translate("Form", "下一页"))
